export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  INVALID_SESSION = 'INVALID_SESSION',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Users
  WRONG_CURRENT_PASSWORD = 'WRONG_CURRENT_PASSWORD',
  INVALID_LOCALE = 'INVALID_LOCALE',
  ONBOARDING_ALREADY_COMPLETED = 'ONBOARDING_ALREADY_COMPLETED',
  ONBOARDING_REQUIRED = 'ONBOARDING_REQUIRED',
  EMPTY_ONBOARDING_RESPONSES = 'EMPTY_ONBOARDING_RESPONSES',
  INVALID_BACKGROUND = 'INVALID_BACKGROUND',
  INVALID_GOALS = 'INVALID_GOALS',
  INVALID_INTERESTS = 'INVALID_INTERESTS',
  INTERESTS_PARSE_ERROR = 'INTERESTS_PARSE_ERROR',
  INTERESTS_COUNT_INVALID = 'INTERESTS_COUNT_INVALID',

  // General
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
